##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
robot: 'xArm'
collision_spheres:
  link_base:
    - center: [0.0, 0.0, 0.05]
      radius: 0.06
    - center: [0.0, 0.0, 0.1]
      radius: 0.06
    - center: [0.0, 0.0, 0.15]
      radius: 0.06
  link1:
    - center: [0.0, 0.0, -0.06]
      radius: 0.06
    - center: [0.0, -0.015, -0.005]
      radius: 0.06
    - center: [0.0, 0.04, 0.0]
      radius: 0.06
  link2:
    - center: [0.0, 0.0, 0.09]
      radius: 0.06
    - center: [0.0, -0.055, 0.09]
      radius: 0.06
    - center: [0.0, -0.11, 0.09]
      radius: 0.06
    - center: [0.0, -0.11, 0.045]
      radius: 0.06
    - center: [0.0, -0.11, 0.0]
      radius: 0.06
    - center: [0.0, -0.16, 0.0]
      radius: 0.06
  link3:
    - center: [0.0, 0.0, -0.1]
      radius: 0.065
    - center: [0.0, 0.0, -0.03]
      radius: 0.065
    - center: [0.04, 0.02, 0.0]
      radius: 0.065
    - center: [0.04, -0.04, 0.0]
      radius: 0.065
  link4:
    - center: [0.0, 0.0, 0.09]
      radius: 0.065
    - center: [0.04, -0.045, 0.09]
      radius: 0.065
    - center: [0.08, -0.09, 0.09]
      radius: 0.065
    - center: [0.08, -0.09, 0.05]
      radius: 0.065
    - center: [0.08, -0.09, 0.0]
      radius: 0.065
    - center: [0.08, -0.15, 0.0]
      radius: 0.065
  link5:
    - center: [0.0, 0.05, 0.0]
      radius: 0.06
    - center: [0.0, 0.05, -0.05]
      radius: 0.06
    - center: [0.0, 0.03, -0.1]
      radius: 0.06
    - center: [0.0, 0.0, -0.15]
      radius: 0.06
  link6:
    - center: [0.0, 0.0, 0.0]
      radius: 0.05
    - center: [0.075, 0.0, 0.0]
      radius: 0.05
    - center: [0.075, 0.05, 0.0]
      radius: 0.05
    - center: [0.0, 0.0, 0.03]
      radius: 0.05
    - center: [0.035, 0.0, 0.03]
      radius: 0.05
  link7:
    - center: [0.0, 0.0, 0.0]
      radius: 0.05